Testng hw
SMeleshk/TAF_AQA18_onl pull request #1
Opened 2022-12-04 00:05 UTC by SMeleshk

2022-12-06 16:13 UTC, wildpioneer requested changes

2022-12-06 16:13 UTC, wildpioneer commented on src/test/java/tests/CalculatorDivDoubleTest.java
> +        Assert.assertEquals(isXInfinite, true, "неверное частное");
Все верно по сути , но я бы сократил до:
Assert.assertTrue(Double.isInfinite(calculator.divDouble(1, 10E-310)), "неверное частное");

2022-12-06 16:13 UTC, wildpioneer commented on src/test/java/tests/CalculatorDivDoubleTest.java
> +        Assert.assertEquals(isXInfinite, true, "неверное частное");
Assert.assertEquals(???, true) -> Assert.assertTrue(????)

2022-12-06 16:13 UTC, wildpioneer commented on src/test/java/tests/CalculatorDivDoubleTest.java
> +    public void testDivision2(){
Применяй сразу единое форматирование кода:
public void method_name() {

А то у тебя то есть пробел перед фигурной скобкой, то его нет

2022-12-06 19:21 UTC, SMeleshk commented on src/test/java/tests/CalculatorDivDoubleTest.java
> +        Assert.assertEquals(isXInfinite, true, "неверное частное");
сократила во всех местах, где нашла

2022-12-06 19:22 UTC, SMeleshk commented on src/test/java/tests/CalculatorDivDoubleTest.java
> +        Assert.assertEquals(isXInfinite, true, "неверное частное");
исправила

2022-12-06 19:22 UTC, SMeleshk commented on src/test/java/tests/CalculatorDivDoubleTest.java
> +    public void testDivision2(){
перепроверила код и исправила

2022-12-13 10:37 UTC, wildpioneer requested changes

2022-12-13 10:37 UTC, wildpioneer commented on src/test/java/tests/Calculator.java
> +    public int divInt (int a, int b) {
Для чего нужны разные названия методов? Повторить полиморфизм.

2022-12-13 10:37 UTC, wildpioneer commented on src/test/java/tests/CalculatorDivIntTest.java
> +        calculator.divInt(1, 0);
Отсутствуют тесты на:
1. @Parameters
2. priority
3. Double.NaN

2022-12-17 22:05 UTC, SMeleshk commented on src/test/java/tests/CalculatorDivIntTest.java
> +        calculator.divInt(1, 0);
1. Добавила в CalculatorDivDoubleTest
2. priority находится в CalculatorDivIntTest, строка номер 15
3. Добавила в CalculatorDivDoubleTest

2022-12-17 22:05 UTC, SMeleshk commented on src/test/java/tests/Calculator.java
> +    public int divInt (int a, int b) {
Перегрузила метод

2022-12-20 15:06 UTC, wildpioneer commented
Проверено

2022-12-20 15:06 UTC, closed without merging