Cucumber SauceDemo HW
SMeleshk/TAF_AQA18_onl pull request #11
Opened 2023-02-05 21:08 UTC by SMeleshk

2023-02-07 14:51 UTC, wildpioneer requested changes

2023-02-07 14:51 UTC, wildpioneer commented on src/test/java/stepDefs/E2EStepDefs.java
> +
@After метод забыла - поэтому браузер не закрывается после выполнения тестов

2023-02-07 15:37 UTC, SMeleshk commented on src/test/java/stepDefs/E2EStepDefs.java
> +
Исправила

2023-02-27 20:06 UTC, wildpioneer commented
Проверено

2023-02-27 20:06 UTC, closed without merging