HW Selenium Advanced
SMeleshk/TAF_AQA18_onl pull request #4
Opened 2022-12-17 21:30 UTC by SMeleshk

2022-12-20 15:24 UTC, wildpioneer requested changes

2022-12-20 15:24 UTC, wildpioneer commented on src/test/java/tests/DynamicControlsTest.java
> +    Actions actions = new Actions(driver);
??? А что это. Из-за этого тесты не запускаются

2022-12-20 15:31 UTC, SMeleshk commented on src/test/java/tests/DynamicControlsTest.java
> +    Actions actions = new Actions(driver);
Хотела вынести в BaseTest и забыла. Исправлено

2023-01-16 17:51 UTC, wildpioneer commented
Проверены изменения

2023-01-16 17:51 UTC, closed without merging