HW PageObject E2E test
SMeleshk/TAF_AQA18_onl pull request #5
Opened 2022-12-19 20:46 UTC by SMeleshk

2022-12-20 15:18 UTC, wildpioneer requested changes

2022-12-20 15:18 UTC, wildpioneer commented on src/test/java/tests/E2ETest.java
> +        Assert.assertEquals(productsStep.getBadgeText(), "1");
Один тест - одна ключевая проверка

2023-01-08 19:06 UTC, SMeleshk commented on src/test/java/tests/E2ETest.java
> +        Assert.assertEquals(productsStep.getBadgeText(), "1");
Сделала новый тест, соответствующий требованиям end-to-end теста.

2023-01-16 17:52 UTC, wildpioneer commented
Проверены изменения

2023-01-16 17:52 UTC, closed without merging