Wrappers HW
SMeleshk/TAF_AQA18_onl pull request #6
Opened 2023-01-16 14:35 UTC by SMeleshk

2023-01-16 18:07 UTC, wildpioneer requested changes

2023-01-16 18:07 UTC, wildpioneer commented on src/test/java/elements/DropDownMenu.java
> +        dropDown.click();
А почему ты кликаешь на DropDown при его инициализации??

2023-01-16 18:07 UTC, wildpioneer commented on src/test/java/elements/DropDownMenu.java
> +        for (WebElement webElement : dropDown.findElements(By.xpath("child::div/ul/li"))) {
Мне не нравиться selector-ор тут - что-то ты намудрила

2023-01-16 18:07 UTC, wildpioneer commented on src/test/java/elements/DropDownMenu.java
> +
Отсутствует метод для работы с полем поиска в DropDown

2023-01-30 19:30 UTC, SMeleshk commented on src/test/java/elements/DropDownMenu.java
> +        for (WebElement webElement : dropDown.findElements(By.xpath("child::div/ul/li"))) {
Исправила.

2023-01-30 19:31 UTC, SMeleshk commented on src/test/java/elements/DropDownMenu.java
> +
Сделала 2 метода: 1 - search, 2 - searchAndSelectFirst

2023-01-30 19:34 UTC, SMeleshk commented on src/test/java/elements/DropDownMenu.java
> +        dropDown.click();
Клик нужен, чтобы списки могли наполнится веб-элементами. Иначе никакие wait не помогают.
В дебаг режиме проверила, что при отсутствии клика списки НЕ заполняются, из-за чего все тесты падают.
У меня больше нет идей, как решить данную проблему.

2023-02-07 14:52 UTC, wildpioneer commented
Проверено

2023-02-07 14:52 UTC, closed without merging